version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"               # location of your requirements.txt
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    # only bump direct dependencies:
    allow:
      - dependency-type: "direct"
    # auto-merge minor & patch
    automerge: true
    automerge-type: "pr"
    # group TensorRT and its libs/bindings
    groups:
      tensorrt:
        patterns:
          - "^tensorrt$"
          - "^tensorrt\\-cu12\\-libs$"
          - "^tensorrt\\-cu12\\-bindings$"
        # optional human-friendly title
        group-name: "TensorRT & related packages"
