version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"               
    schedule:
      interval: "weekly"
    groups:
      tensorrt:
        patterns:
          - "^tensorrt$"
          - "^tensorrt\\-cu12\\-libs$"
          - "^tensorrt\\-cu12\\-bindings$"
