version: 2
updates:
  - package-ecosystem: pip
    directory: "/"               # your pip manifest lives here (e.g. requirements.txt or pyproject.toml)
    schedule:
      interval: weekly
    automerged_updates:
      - match:
          update_types:
            - "version-update:semver-patch"
            - "version-update:semver-minor"
            - "version-update:pin"
    groups:
      tensorrt:
        patterns:
          - "^tensorrt$"
          - "^tensorrt_cu12_bindings$"
          - "^tensorrt_cu12_libs$"
