services:
  wyoming-whisper-trt:
    image: captnspdr/wyoming-whisper-trt:latest
    container_name: wyoming-whisper-trt
    ports:
      - 10300:10300
    environment:
      - MODEL=base
      - LANGUAGE=auto
      - DEVICE=cuda
      - DATA_DIR=/data
      - DOWNLOAD_DIR=/data/models
    volumes:
      - wyoming-data:/data
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
