services:
  wyoming-whisper-trt:
    image: captnspdr/wyoming-whisper-trt:latest-igpu
    container_name: wyoming-whisper-trt
    environment:
      - MODEL=base
      - LANGUAGE=auto
      - DEVICE=cuda
      - DATA_DIR=/data
      - DOWNLOAD_DIR=/data/models
      - COMPUTE_TYPE=int8
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - wyoming-data:/data
    restart: unless-stopped
    network_mode: host
    runtime: nvidia
