services:
  wyoming-whisper-trt:
    build: .\Dockerfile.igpu
    container_name: wyoming-whisper-trt
    ports:
      - 10300:10300
    restart: unless-stopped
    network_mode: host
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
