services:
  wyoming-whisper-trt:
    context: .
    build: Dockerfile.igpu
    container_name: wyoming-whisper-trt
    ports:
      - 10300:10300
    environment:
      - MODEL=base
      - LANGUAGE=auto
      - DEVICE=cuda
      - DATA_DIR=/data
      - DOWNLOAD_DIR=/data/models
    volumes:
      - wyoming-data:/data
    restart: unless-stopped
    network_mode: host
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
