#!/usr/bin/env python3
"""Create the venv, install requirements, and install torch2trt."""

import argparse
import os
import subprocess
import venv
from pathlib import Path

_DIR = Path(__file__).parent
_PROGRAM_DIR = _DIR.parent
_VENV_DIR = _PROGRAM_DIR / ".venv"
_TORCH2TRT_DIR = (
    _PROGRAM_DIR / "torch2trt"
)  # Update this path if torch2trt is located elsewhere

parser = argparse.ArgumentParser()
parser.add_argument("--dev", action="store_true", help="Install dev requirements")
parser.add_argument(
    "--system_site_packages",
    action="store_true",
    help="Include system site packages in the virtual environment",
    default=False,
)
args = parser.parse_args()

# Create virtual environment
if args.system_site_packages:
    print("Creating virtual environment with access to system site packages...")
builder = venv.EnvBuilder(with_pip=True, system_site_packages=args.system_site_packages)
context = builder.ensure_directories(_VENV_DIR)
builder.create(_VENV_DIR)

# Upgrade dependencies
pip = [context.env_exe, "-m", "pip"]
subprocess.check_call([*pip, "install", "--upgrade", "pip"])
subprocess.check_call([*pip, "install", "--upgrade", "setuptools", "wheel"])

# Install requirements
subprocess.check_call([*pip, "install", "-r", str(_PROGRAM_DIR / "requirements.txt")])

if args.dev:
    # Install dev requirements
    subprocess.check_call(
        [*pip, "install", "-r", str(_PROGRAM_DIR / "requirements_dev.txt")]
    )

# Install torch2trt
os.chdir(_TORCH2TRT_DIR)
subprocess.check_call([context.env_exe, "setup.py", "install"])

# Optionally, return to the original directory
os.chdir(_PROGRAM_DIR)
