name: Pyright
permissions:
  contents: read

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv .venv
          .venv/bin/python -m pip install --upgrade pip
          .venv/bin/python -m pip install -r requirements.txt -r requirements_dev.txt

      - name: Run pyright
        run: .venv/bin/pyright
